// 智鹰系统前端模拟数据层
// 所有数据均为仿真示例，结构与后端 server.js 保持一致

export const leads = [
  {
    id: 'L001', title: '广州市政务数据局大数据治理平台建设项目',
    type: 'bidding', typeName: '招采动作', typeColor: 'blue', score: 94,
    scoreReason: '明确采购预算800万，建设内容（数据目录/数据质量/数据湖）与我司核心产品高度契合；采购意向已公示，窗口期约2周；无明显偏向友商参数。',
    summary: '广州市政务数据局发布采购意向公示，拟建设覆盖47个委办局的统一大数据治理平台，预算800万元，技术要求含数据目录、数据质量、数据安全三大核心功能模块。',
    source: '广东省政府采购网', region: '广东省', city: '广州市',
    status: 'pending', createdAt: '2026-03-21', updatedAt: '2026-03-21',
    nextAction: '立即联系广州局采购处王处长，确认技术需求细节并预约方案汇报',
    budget: 800, department: '广州市政务数据局',
    contact: '王建国', contactRole: '采购处处长',
    tags: ['大数据', '数据治理', '华南区', '近期招标'], deadline: '2026-04-05',
  },
  {
    id: 'L002', title: '成都市数字政府AI大模型平台专项规划跟进',
    type: 'policy', typeName: '政策驱动', typeColor: 'green', score: 78,
    scoreReason: '成都市《数字政府2.0行动方案》明确提到2026年底前建设政务AI大模型，与我司核心产品高度匹配；但预算尚未确认，需实地摸底资金落地情况。',
    summary: '成都市发布《成都市数字政府2.0三年行动方案（2025-2027）》，明确建设政务AI大模型平台赋能40+委办局，由市大数据局统筹牵头。',
    source: '成都市人民政府官网', region: '四川省', city: '成都市',
    status: 'contacting', createdAt: '2026-03-20', updatedAt: '2026-03-21',
    nextAction: '本周预约成都市大数据局规划处李处长，摸底专项资金到位情况',
    budget: null, department: '成都市大数据局',
    contact: '李明远', contactRole: '规划处处长',
    tags: ['AI大模型', '数字政府', '西南区'], deadline: null,
  },
  {
    id: 'L003', title: '深圳市南山区政务云平台二期扩容升级',
    type: 'renewal', typeName: '二次商机', typeColor: 'purple', score: 91,
    scoreReason: '现有平台已运营2.5年，合同维保到期在即；客情基础极好（甲方主任已确认意向）；二期明确新增AI辅助决策模块。',
    summary: '南山区政务服务数据管理局一期大数据平台（我司承建）已运行2.5年，区领导明确要求2026年Q2前完成二期扩容，新增AI辅助决策、数据要素流通等能力。',
    source: '内部CRM老客户维护记录', region: '广东省', city: '深圳市',
    status: 'contacting', createdAt: '2026-03-18', updatedAt: '2026-03-21',
    nextAction: '本周五前提交《二期建设方案建议书》，并安排高层互访确认立项计划',
    budget: 1200, department: '南山区政务服务数据管理局',
    contact: '陈志强', contactRole: '副局长',
    tags: ['老客户', '二次商机', '大模型', '华南区'], deadline: '2026-05-01',
  },
  {
    id: 'L004', title: '重庆市渝北区智慧城市大数据底座分包商机（华为总包）',
    type: 'subcontract', typeName: '友商分包', typeColor: 'orange', score: 82,
    scoreReason: '华为云中标渝北区智慧城市总包（3.5亿），标书中大数据治理模块（预算约1500万）与我司能力高度匹配。',
    summary: '华为技术有限公司中标重庆市渝北区智慧城市建设EPC总包项目（3.5亿），标书中明确大数据治理、数字孪生两个子模块采用分包模式采购。',
    source: '重庆市公共资源交易中心中标公告', region: '重庆市', city: '重庆市',
    status: 'pending', createdAt: '2026-03-19', updatedAt: '2026-03-20',
    nextAction: '联系华为重庆政务云负责人赵总，确认分包计划和我司介入可行性',
    budget: 1500, department: '重庆市渝北区智慧城市建设指挥部',
    contact: '赵磊', contactRole: '华为重庆政务云总监',
    tags: ['分包', '智慧城市', '华为生态', '西南区'], deadline: '2026-04-15',
  },
  {
    id: 'L005', title: '山东省数据要素市场化交易平台建设项目',
    type: 'budget', typeName: '预算专项', typeColor: 'gold', score: 88,
    scoreReason: '山东省财政厅2026年专项债资金已到位（8000万），省大数据局2025年底已完成规划评审，落地确定性强。',
    summary: '山东省大数据局承接省财政厅8000万专项资金，推进全省统一数据要素市场化交易平台建设，包含数据产品登记、数据交易撮合、数据资产评估三大子系统。',
    source: '山东省财政厅预算公开报告 + 山东省大数据局官网', region: '山东省', city: '济南市',
    status: 'contacting', createdAt: '2026-03-17', updatedAt: '2026-03-20',
    nextAction: '下周二赴济南拜访省大数据局孙副局长，携带数据要素产品Demo',
    budget: 8000, department: '山东省大数据局',
    contact: '孙立新', contactRole: '省大数据局副局长',
    tags: ['数据要素', '专项债', '华东区', '高优先级'], deadline: '2026-04-30',
  },
  {
    id: 'L006', title: '北京市海淀区卫健委公共卫生大数据平台',
    type: 'bidding', typeName: '招采动作', typeColor: 'blue', score: 71,
    scoreReason: '招标公告已发布，但存在"海淀区已有合作项目"加分项，中软国际在海淀有存量项目，对我司有一定壁垒。',
    summary: '海淀区卫生健康委员会发布招标公告，拟建设公共卫生大数据预警平台，预算600万，要求承建方有同类医疗大数据项目案例。',
    source: '北京市政府采购网', region: '北京市', city: '北京市',
    status: 'pending', createdAt: '2026-03-21', updatedAt: '2026-03-21',
    nextAction: '研究评分标准，评估竞争力，若参与需提前一周准备医疗大数据案例材料',
    budget: 600, department: '海淀区卫生健康委员会',
    contact: null, contactRole: null,
    tags: ['医疗大数据', '华北区', '评估中'], deadline: '2026-03-31',
  },
  {
    id: 'L007', title: '杭州市拱墅区新局长引发新系统建设意向（人事异动）',
    type: 'personnel', typeName: '人事异动', typeColor: 'cyan', score: 75,
    scoreReason: '老客户西湖区刘局长调任拱墅区大数据局局长，其在西湖区对我司评价极高，属高质量隐性线索。',
    summary: '原杭州市西湖区大数据局刘勇局长（我司西湖区平台一期甲方）已正式调任拱墅区大数据局局长，据内部联系人透露，刘局到任后已提出今年建设统一数据共享交换平台的意向。',
    source: '杭州市政府官网人事任免公告 + 内部联系人', region: '浙江省', city: '杭州市',
    status: 'contacting', createdAt: '2026-03-15', updatedAt: '2026-03-18',
    nextAction: '安排高管与刘局进行一次非正式拜会，建立新岗位初期的关系纽带',
    budget: null, department: '杭州市拱墅区大数据局',
    contact: '刘勇', contactRole: '局长（原西湖区老客户）',
    tags: ['人事异动', '人脉拓展', '华东区'], deadline: null,
  },
  {
    id: 'L008', title: '武汉市政务服务局一网通办平台AI化智能改造',
    type: 'policy', typeName: '政策驱动', typeColor: 'green', score: 65,
    scoreReason: '政策方向明确，但武汉市今年财政预算偏紧，项目可能延后至Q3。腾讯云在武汉竞争优势明显。',
    summary: '武汉市政务服务和大数据管理局发布《2026年数字政府工作要点》，明确推进一网通办平台AI升级，引入智能审批、智能客服等能力，计划择机采购。',
    source: '武汉市政务服务局官网', region: '湖北省', city: '武汉市',
    status: 'pending', createdAt: '2026-03-16', updatedAt: '2026-03-16',
    nextAction: '列入观察，2026年Q2再跟进预算计划确认情况',
    budget: null, department: '武汉市政务服务和大数据管理局',
    contact: null, contactRole: null,
    tags: ['一网通办', 'AI改造', '中南区', '观察期'], deadline: null,
  },
  {
    id: 'L009', title: '福建省数字政府大模型能力底座集采项目',
    type: 'bidding', typeName: '招采动作', typeColor: 'blue', score: 87,
    scoreReason: '省级统一集采，影响力大；要求"本地化部署大模型"，与我司私有化产品线高度契合。',
    summary: '福建省大数据管理局发布2026年度政务AI大模型能力底座集中采购公示，计划统一采购并部署可供全省40个省直部门调用的政务专用大模型底座，预算3200万。',
    source: '福建省政府采购网', region: '福建省', city: '福州市',
    status: 'contacting', createdAt: '2026-03-14', updatedAt: '2026-03-19',
    nextAction: '已安排下周三技术对接，需提前准备大模型省级部署方案和性能测试报告',
    budget: 3200, department: '福建省大数据管理局',
    contact: '张鹏飞', contactRole: '技术处副处长',
    tags: ['大模型', '省级集采', '华东区', '跟进中'], deadline: '2026-04-20',
  },
  {
    id: 'L010', title: '南京市栖霞区智慧园区数据中台需求（展会获取）',
    type: 'exhibition', typeName: '展会活动', typeColor: 'magenta', score: 58,
    scoreReason: '展会交流阶段，线索较初级；对方表达兴趣但未明确预算和时间节点，需进一步筛选。',
    summary: '在2026中国数字政府大会上，南京市栖霞区经济发展局信息化负责人咨询，表达了为高新区建设统一数据中台的想法，但未透露具体预算。',
    source: '2026中国数字政府大会（线下）', region: '江苏省', city: '南京市',
    status: 'pending', createdAt: '2026-03-10', updatedAt: '2026-03-10',
    nextAction: '发送产品介绍资料，安排一次30分钟线上摸底交流',
    budget: null, department: '南京市栖霞区经济发展局',
    contact: '周小华', contactRole: '信息化科科长',
    tags: ['展会线索', '华东区', '待确认'], deadline: null,
  },
  {
    id: 'L011', title: '内蒙古农业厅智慧农业大数据平台（专项拨款到位）',
    type: 'budget', typeName: '预算专项', typeColor: 'gold', score: 80,
    scoreReason: '中央农业数字化专项拨款已到位4000万，竞争格局相对空白，是拓展新赛道的稀缺窗口期。',
    summary: '内蒙古自治区农业农村厅获得中央数字农业专项资金4000万元，计划2026年内完成智慧农业大数据平台建设，涵盖农业物联网、农产品溯源、农业生产预警三大模块。',
    source: '农业农村部官网财政拨款公告', region: '内蒙古', city: '呼和浩特市',
    status: 'pending', createdAt: '2026-03-20', updatedAt: '2026-03-21',
    nextAction: '评估出行计划，本月内安排初次接触',
    budget: 4000, department: '内蒙古自治区农业农村厅',
    contact: null, contactRole: null,
    tags: ['智慧农业', '专项资金', '北方区'], deadline: null,
  },
  {
    id: 'L012', title: '上海市静安区数据共享交换平台废标重招',
    type: 'bidding', typeName: '招采动作', typeColor: 'blue', score: 83,
    scoreReason: '第一次因技术评审分歧废标（无明显控标），二次招标评分标准更公平；我司已提前完成竞品对比分析。',
    summary: '上海市静安区大数据中心数据共享交换平台采购项目因技术分歧发出废标公告，现已发布二次招标，预算调整至900万。',
    source: '上海市政府采购云平台', region: '上海市', city: '上海市',
    status: 'filed', createdAt: '2026-03-12', updatedAt: '2026-03-20',
    nextAction: '华东区交付团队本周完成投标方案初稿',
    budget: 900, department: '上海市静安区大数据中心',
    contact: '吴建波', contactRole: '项目处处长',
    tags: ['废标重招', '已立项', '华东区'], deadline: '2026-04-10',
  },
  {
    id: 'L013', title: '南昌市公安局警务大数据综合应用平台（内部引荐）',
    type: 'manual', typeName: '手工录入', typeColor: 'default', score: 85,
    scoreReason: '通过行业峰会高层引荐获取；项目已完成内部立项，预算1800万，拟于5月发布招标，成单概率极高。',
    summary: '通过省公安厅大数据局引荐，南昌市公安局副局长张伟国邀约方案交流，该项目已完成内部立项，预算1800万，拟于2026年5月正式发布招标公告。',
    source: '行业峰会高层引荐（手工录入）', region: '江西省', city: '南昌市',
    status: 'contacting', createdAt: '2026-03-05', updatedAt: '2026-03-21',
    nextAction: '本周五上门汇报方案，重点演示警务AI大模型与大数据融合应用Demo',
    budget: 1800, department: '南昌市公安局',
    contact: '张伟国', contactRole: '副局长（分管信息化）',
    tags: ['公共安全', '高管引荐', '华东区', '高优先级'], deadline: '2026-05-10',
  },
  {
    id: 'L014', title: '天津市滨海新区数字城管运营中心二期建设',
    type: 'renewal', typeName: '二次商机', typeColor: 'purple', score: 76,
    scoreReason: '滨海新区城管平台一期即将到期；甲方满意度高，有明确升级意愿，赢率预计>85%。',
    summary: '天津市滨海新区城市管理委员会一期数字城管平台三年运维合同2026年6月到期，区城管委主任已提出启动二期智能化升级方案研讨。',
    source: '内部CRM老客户维保到期预警', region: '天津市', city: '天津市',
    status: 'contacting', createdAt: '2026-03-03', updatedAt: '2026-03-19',
    nextAction: '本月内提交《二期智能化升级方案建议书》，附上AI辅助监督新功能演示',
    budget: 650, department: '天津市滨海新区城市管理委员会',
    contact: '许明刚', contactRole: '城管委主任',
    tags: ['老客户续签', '城市管理', '华北区'], deadline: '2026-05-30',
  },
  {
    id: 'L015', title: '贵州省大数据局公共数据开放平台建设',
    type: 'policy', typeName: '政策驱动', typeColor: 'green', score: 62,
    scoreReason: '贵州政策积极，但本地供应商生态壁垒较深，需评估是否值得投入资源拓展。',
    summary: '贵州省大数据局发布《贵州省公共数据开放工作方案》，明确2026年底前建设省级脱敏数据开放平台。',
    source: '贵州省大数据发展管理局官网', region: '贵州省', city: '贵阳市',
    status: 'pending', createdAt: '2026-03-08', updatedAt: '2026-03-08',
    nextAction: '评估贵州市场竞争格局，确认是否纳入2026年优先拓展区域',
    budget: null, department: '贵州省大数据发展管理局',
    contact: null, contactRole: null,
    tags: ['数据开放', '西南区', '待评估'], deadline: null,
  },
  {
    id: 'L016', title: '西安市雁塔区政务服务中心数字化转型项目',
    type: 'bidding', typeName: '招采动作', typeColor: 'blue', score: 79,
    scoreReason: '陕西省数字政府专项试点城市，雁塔区预算已公示550万，竞争格局相对空白（无强势本地供应商）。',
    summary: '西安市雁塔区政务服务中心发布采购意向公示，拟建设以AI审批和数据看板为核心的新一代政务服务数字化系统，总预算550万元。',
    source: '陕西省政府采购网', region: '陕西省', city: '西安市',
    status: 'pending', createdAt: '2026-03-20', updatedAt: '2026-03-21',
    nextAction: '本周内向西安区域负责人推送线索，争取本月完成首次拜访',
    budget: 550, department: '西安市雁塔区政务服务中心',
    contact: null, contactRole: null,
    tags: ['政务服务', '西北区', '新窗口'], deadline: '2026-04-18',
  },
  {
    id: 'L017', title: '黑龙江省农业农村厅乡村振兴数字平台（中央补助资金）',
    type: 'budget', typeName: '预算专项', typeColor: 'gold', score: 73,
    scoreReason: '中央乡村振兴补助资金3000万到位，省厅已成立专项工作组，建设时序明确，建议尽快介入。',
    summary: '黑龙江省农业农村厅获得中央财政乡村振兴数字化专项补助3000万元，建设覆盖全省农业生产、农村电商、惠农政策三大场景的数字平台。',
    source: '黑龙江省财政厅拨款公告', region: '黑龙江省', city: '哈尔滨市',
    status: 'pending', createdAt: '2026-03-19', updatedAt: '2026-03-21',
    nextAction: '联系东北区省级农业厅资源，本月内完成首次电话摸底',
    budget: 3000, department: '黑龙江省农业农村厅',
    contact: null, contactRole: null,
    tags: ['乡村振兴', '农业数字化', '东北区', '专项资金'], deadline: null,
  },
  {
    id: 'L018', title: '合肥市包河区数字城市大脑二期（老客分包转直客）',
    type: 'renewal', typeName: '二次商机', typeColor: 'purple', score: 86,
    scoreReason: '一期由中软国际总包，我司为数据中台分包商；甲方对我司满意度高于总包商，二期有意直接发包，赢率>80%。',
    summary: '合肥市包河区城市大脑一期（我司数据中台分包）运行良好，区管委会已获批二期建设资金1400万，区主任在沟通中透露希望本次与我司直接签署框架协议。',
    source: '内部CRM客户回访记录', region: '安徽省', city: '合肥市',
    status: 'contacting', createdAt: '2026-03-13', updatedAt: '2026-03-20',
    nextAction: '华东区客户总监本周四与区管委周主任会谈，推进框架协议签署事宜',
    budget: 1400, department: '合肥市包河区城市管理委员会',
    contact: '周鹏程', contactRole: '区管委主任',
    tags: ['老客直采', '二次商机', '华东区', '高赢率'], deadline: '2026-05-20',
  },
  {
    id: 'L019', title: '厦门市思明区智慧社区数字化管理平台招标',
    type: 'bidding', typeName: '招采动作', typeColor: 'blue', score: 68,
    scoreReason: '招标金额480万，技术门槛适中；中建信科在厦门有稳固存量，但评分未明显设限，存在入围机会。',
    summary: '厦门市思明区民政局发布智慧社区数字化管理平台招标公告，涵盖社区事务网格化管理、老年服务智能预警、政务App端集成三大功能。',
    source: '厦门市政府采购网', region: '福建省', city: '厦门市',
    status: 'pending', createdAt: '2026-03-18', updatedAt: '2026-03-19',
    nextAction: '下载招标文件深度分析评分标准，评估竞标可行性',
    budget: 480, department: '厦门市思明区民政局',
    contact: null, contactRole: null,
    tags: ['智慧社区', '华东区', '评估中'], deadline: '2026-04-08',
  },
  {
    id: 'L020', title: '郑州市大数据局新局长完成述职，明确推进数据共享工程',
    type: 'personnel', typeName: '人事异动', typeColor: 'cyan', score: 77,
    scoreReason: '新局长来自省大数据局，与我司省级项目组有工作接触；上任三周已明确点名推进省市数据共享，属高优窗口期线索。',
    summary: '郑州市大数据局新局长贺晓峰（原河南省大数据局处长）于3月初正式履职，在全局干部大会上明确将省市跨层级数据共享平台建设列为今年首要任务。',
    source: '郑州市政府官网 + 内部人脉信息', region: '河南省', city: '郑州市',
    status: 'pending', createdAt: '2026-03-16', updatedAt: '2026-03-21',
    nextAction: '通过省级项目组联系人，以非正式方式向贺局请教政策方向，建立初步关系',
    budget: null, department: '郑州市大数据局',
    contact: '贺晓峰', contactRole: '局长（新任）',
    tags: ['人事异动', '省市联动', '华中区', '人脉切入'], deadline: null,
  },
  {
    id: 'L021', title: '苏州工业园区数字政府"AI+数据"综合改造（展会获取）',
    type: 'exhibition', typeName: '展会活动', typeColor: 'magenta', score: 72,
    scoreReason: '对方信息化主任主动留名片，表达了强烈兴趣；园区AI预算充足，具备快速决策能力，展会线索中难得的高质量。',
    summary: '在2026数字中国峰会上，苏州工业园区管理委员会信息化处主任张宇晨主动接触，表达推进园区政务数字化"AI+数据"综合改造的意向，明确说明预算来自园区自筹，决策链条短。',
    source: '2026数字中国峰会（线下）', region: '江苏省', city: '苏州市',
    status: 'contacting', createdAt: '2026-03-11', updatedAt: '2026-03-20',
    nextAction: '本周发送定制方案PPT，争取下周完成线上深度交流',
    budget: 700, department: '苏州工业园区管理委员会',
    contact: '张宇晨', contactRole: '信息化处主任',
    tags: ['展会高质量', '园区', '华东区', '快决策'], deadline: '2026-04-25',
  },
]

export const policies = [
  {
    id: 'P001', title: '国家数据局《数字中国建设2026年工作要点》',
    level: 'national', levelName: '国家级', region: '全国', publishedAt: '2026-03-01',
    summary: '明确2026年推进政务数据跨层级共享、建立全国一体化数据基础设施体系、推进政务AI大模型试点等12项重点任务。',
    relevantTasks: ['推进各省市统一大数据底座建设', '部署政务AI大模型能力平台', '完善数据要素市场化交易体系'],
    potentialDepts: ['各省市大数据局', '各省市数字化转型主管部门'],
    budgetSignal: '各省市配套专项资金落地是关键跟进节点', score: 90,
  },
  {
    id: 'P002', title: '广东省《数字政府建设三年行动方案（2025-2027）》',
    level: 'provincial', levelName: '省级', region: '广东省', publishedAt: '2025-11-15',
    summary: '明确三年内建设全省统一政务云底座、政务数据湖、AI大模型服务平台，重点推进珠三角城市群数字化协同。',
    relevantTasks: ['建设省级政务数据湖', '市级数字政府标准化建设试点', '政务AI应用场景落地'],
    potentialDepts: ['广东省政务服务数据管理局', '各市大数据局'],
    budgetSignal: '广东省财政2026年数字政府专项预算已公示：12亿元', score: 95,
  },
  {
    id: 'P003', title: '上海市《城市数字化转型"十四五"规划中期评估》',
    level: 'provincial', levelName: '市级', region: '上海市', publishedAt: '2026-02-10',
    summary: '评估显示政务大模型能力落地率不及预期，2026年需重点补强政务大模型能力建设。',
    relevantTasks: ['补强政务大模型能力', '推进城市感知网络AI升级', '完成16个区数据共享专项'],
    potentialDepts: ['上海市大数据中心', '各区大数据管理部门'],
    budgetSignal: '市级补充专项预算预计2026年Q2公示', score: 82,
  },
  {
    id: 'P004', title: '成都市《数字政府2.0三年行动方案（2026-2028）》',
    level: 'city', levelName: '市级', region: '四川省', publishedAt: '2026-03-05',
    summary: '明确建立覆盖全市政务部门的政务AI大模型能力底座，推进数据要素市场化试点。',
    relevantTasks: ['部署政务AI大模型底座', '建设数据要素流通试验区', '扩大政务数据共享覆盖范围'],
    potentialDepts: ['成都市大数据局', '成都市发展改革委'],
    budgetSignal: '专项债申报中，预计2026年Q3资金到位', score: 78,
  },
  {
    id: 'P005', title: '浙江省《关于加快推进数字政府迭代升级的若干措施》',
    level: 'provincial', levelName: '省级', region: '浙江省', publishedAt: '2026-01-20',
    summary: '出台16条措施加速政府数字化，重点推进AI赋能政务服务、打通省市县三级数据壁垒。',
    relevantTasks: ['AI赋能政务服务升级改造', '县级数字政府标准化建设', '建立全省统一数据资产管理平台'],
    potentialDepts: ['浙江省大数据发展管理局', '各地市数字化改革办公室'],
    budgetSignal: '省级预算已公示，各市配套资金预计Q2落地', score: 88,
  },
  {
    id: 'P006', title: '山东省《加快推进数字强省建设三年行动计划》',
    level: 'provincial', levelName: '省级', region: '山东省', publishedAt: '2026-02-18',
    summary: '三年内在全省建设统一数字底座，重点在数据要素市场化、政务服务一体化两大方向发力。',
    relevantTasks: ['建设全省统一数据要素交易平台', '推进政务服务一体化改造', '推广AI辅助政务决策'],
    potentialDepts: ['山东省大数据局', '省发改委'],
    budgetSignal: '8000万专项债资金已获批', score: 91,
  },
]

export const bids = [
  {
    id: 'B001', title: '广州市政务数据局大数据治理平台建设项目（采购意向公示）',
    amount: 800, region: '广东省', city: '广州市', statusKey: 'intention', statusName: '采购意向',
    statusColor: 'orange', publishedAt: '2026-03-21', deadline: '2026-04-05',
    department: '广州市政务数据局', source: '广东省政府采购网',
    description: '建设覆盖全市47个委办局的统一大数据治理平台，包含数据目录、数据质量、数据安全三大核心功能。',
    hasSubcontract: false, competitors: [], winner: null, policyRef: 'P002',
  },
  {
    id: 'B002', title: '上海市静安区数据共享交换平台（废标重招）',
    amount: 900, region: '上海市', city: '上海市', statusKey: 'bidding', statusName: '正在招标',
    statusColor: 'blue', publishedAt: '2026-03-12', deadline: '2026-04-10',
    department: '上海市静安区大数据中心', source: '上海市政府采购云平台',
    description: '第一次因技术分歧废标并重新发布，预算调增100万，技术要求补充了大模型接入能力。',
    hasSubcontract: false, competitors: ['中软国际', '神州信息'], winner: null, policyRef: 'P003',
  },
  {
    id: 'B003', title: '重庆市渝北区智慧城市建设EPC总包（华为中标）',
    amount: 35000, region: '重庆市', city: '重庆市', statusKey: 'awarded', statusName: '已中标',
    statusColor: 'green', publishedAt: '2026-03-01', deadline: null,
    department: '重庆市渝北区智慧城市建设指挥部', source: '重庆市公共资源交易平台',
    description: '华为中标智慧城市EPC总包，标书中含大数据治理子模块（约1500万）将对外分包。',
    hasSubcontract: true, competitors: [], winner: '华为技术有限公司',
    subcontractNote: '大数据治理模块（约1500万）将对外分包，是我司借船出海的切入点',
    policyRef: null,
  },
  {
    id: 'B004', title: '福建省政务AI大模型能力底座集中采购',
    amount: 3200, region: '福建省', city: '福州市', statusKey: 'bidding', statusName: '正在招标',
    statusColor: 'blue', publishedAt: '2026-03-14', deadline: '2026-04-20',
    department: '福建省大数据管理局', source: '福建省政府采购网',
    description: '省级统一集采政务专用AI大模型底座，要求支持本地化私有化部署，面向全省40个省直部门提供服务。',
    hasSubcontract: false, competitors: ['华为云', '百度智能云'], winner: null, policyRef: null,
  },
  {
    id: 'B005', title: '北京市丰台区数字政务服务平台AI升级改造',
    amount: 1100, region: '北京市', city: '北京市', statusKey: 'bidding', statusName: '正在招标',
    statusColor: 'blue', publishedAt: '2026-03-10', deadline: '2026-03-28',
    department: '北京市丰台区政务服务局', source: '北京市政府采购网',
    description: '对现有政务服务平台进行AI化升级，新增智能审批、AI客服、数据看板等功能。',
    hasSubcontract: false, competitors: ['中软国际', '思特奇'], winner: null, policyRef: null,
  },
  {
    id: 'B006', title: '辽宁省营口市公安局警务大数据平台（废标重招预告）',
    amount: 2400, region: '辽宁省', city: '营口市', statusKey: 'failed', statusName: '已废标',
    statusColor: 'red', publishedAt: '2026-02-20', deadline: null,
    department: '营口市公安局', source: '辽宁省公共资源交易中心',
    description: '因预算调整原因发布废标公告，预计3月底重新发布更新后的采购需求。',
    hasSubcontract: false, competitors: ['中国电科', '海康威视'], winner: null, policyRef: null,
  },
]

export const competitors = [
  {
    id: 'C001', name: '华为技术有限公司（政务云）', shortName: '华为云',
    type: '整合型平台商',
    strength: ['政府关系极强', '硬件生态完整', '品牌背书强', '央国企首选供应商'],
    weakness: ['软件定制弹性不足', '服务成本高昂', '分包经常出现质量问题'],
    recentWins: [
      { project: '重庆市渝北区智慧城市EPC', amount: 35000, date: '2026-03', region: '重庆' },
      { project: '广东省统一政务云底座', amount: 28000, date: '2026-01', region: '广东' },
      { project: '湖南省大数据中心扩容', amount: 9500, date: '2025-11', region: '湖南' },
    ],
    ecosystemPartners: ['新华三', '中软国际', '软通动力'],
    coverageRegions: ['广东', '重庆', '四川', '北京', '湖南', '河南'],
  },
  {
    id: 'C002', name: '中软国际科技集团', shortName: '中软国际',
    type: '软件集成型',
    strength: ['华为生态深度绑定', '人力资源成本低', '承接能力强', '全国布局成熟'],
    weakness: ['自研产品化程度低', '过度依赖华为', '大模型能力弱'],
    recentWins: [
      { project: '北京市政务数据共享交换平台', amount: 1800, date: '2026-02', region: '北京' },
      { project: '河南省大数据中心扩容', amount: 3200, date: '2025-11', region: '河南' },
    ],
    ecosystemPartners: ['华为云', '毕马威', '安永'],
    coverageRegions: ['北京', '河南', '广东', '上海'],
  },
  {
    id: 'C003', name: '浪潮软件集团', shortName: '浪潮',
    type: '平台型老牌玩家',
    strength: ['山东根据地牢固', '政务领域深厚资源', '本地化服务好'],
    weakness: ['AI大模型能力相对滞后', '产品迭代慢', '跨省扩张难'],
    recentWins: [
      { project: '山东省电子政务云平台扩容', amount: 8500, date: '2026-03', region: '山东' },
      { project: '陕西省政务数据库建设', amount: 2100, date: '2025-10', region: '陕西' },
    ],
    ecosystemPartners: ['IBM', '甲骨文'],
    coverageRegions: ['山东', '江苏', '陕西', '北京'],
  },
  {
    id: 'C004', name: '神州信息', shortName: '神州信息',
    type: '行业解决方案型',
    strength: ['金融与政务双行业经验', '交付规范化程度高', '大型项目管理能力强'],
    weakness: ['创新速度偏慢', '区域客情深度不均', '方案同质化明显'],
    recentWins: [
      { project: '上海市某区数据共享交换平台', amount: 1600, date: '2026-02', region: '上海' },
      { project: '天津市政务服务中台升级', amount: 1300, date: '2025-12', region: '天津' },
    ],
    ecosystemPartners: ['腾讯云', '华为云', '金蝶'],
    coverageRegions: ['上海', '天津', '北京', '河北'],
  },
  {
    id: 'C005', name: '东软集团（政务事业部）', shortName: '东软',
    type: '行业深耕型',
    strength: ['医疗政务场景经验丰富', '本地化实施团队稳定', '集成能力均衡'],
    weakness: ['品牌势能中等', '大模型能力建设较晚', '超大型项目案例偏少'],
    recentWins: [
      { project: '沈阳市政务服务能力提升项目', amount: 980, date: '2026-01', region: '辽宁' },
      { project: '长春市公共数据治理平台', amount: 1250, date: '2025-11', region: '吉林' },
    ],
    ecosystemPartners: ['华三', '阿里云', '腾讯云'],
    coverageRegions: ['辽宁', '吉林', '黑龙江', '山东'],
  },
  {
    id: 'C006', name: '南威软件股份有限公司', shortName: '南威软件',
    type: '政务应用产品型',
    strength: ['电子政务产品线完整', '福建区域关系深', '政务服务场景积累厚'],
    weakness: ['跨区域扩张速度有限', '高端咨询能力偏弱', '生态号召力一般'],
    recentWins: [
      { project: '福州市一网通办能力提升', amount: 880, date: '2026-03', region: '福建' },
      { project: '泉州市数字政府门户改造', amount: 760, date: '2025-12', region: '福建' },
    ],
    ecosystemPartners: ['华为云', '麒麟软件', '统信软件'],
    coverageRegions: ['福建', '浙江', '江西'],
  },
  {
    id: 'C007', name: '太极股份', shortName: '太极',
    type: '央企背景集成型',
    strength: ['央国企项目资源强', '安全合规优势明显', '部委级项目经验丰富'],
    weakness: ['商务流程偏重', '交付响应速度一般', '成本控制压力大'],
    recentWins: [
      { project: '某部委数据治理专项', amount: 4200, date: '2026-02', region: '北京' },
      { project: '西安市政务云安全加固项目', amount: 1500, date: '2025-10', region: '陕西' },
    ],
    ecosystemPartners: ['中国电子', '中电科', '麒麟软件'],
    coverageRegions: ['北京', '陕西', '湖北', '广东'],
  },
  {
    id: 'C008', name: '软通动力（政企数字化）', shortName: '软通动力',
    type: '生态协同型',
    strength: ['生态合作广', '交付团队规模大', '成本弹性较好'],
    weakness: ['自研产品差异化不足', '高层客情沉淀较弱', '复杂项目利润率低'],
    recentWins: [
      { project: '深圳市某区政务数据底座扩容', amount: 1180, date: '2026-01', region: '广东' },
      { project: '成都市政务AI应用试点', amount: 920, date: '2025-11', region: '四川' },
    ],
    ecosystemPartners: ['华为云', '腾讯云', '中软国际'],
    coverageRegions: ['广东', '四川', '重庆', '江苏'],
  },
]

export const customers = [
  {
    id: 'CU001', name: '广州市政务服务数据管理局', abbr: '广州政数局',
    region: '广东省', city: '广州市', type: '省会城市核心局',
    projects: [
      { name: '广州市政务数据共享交换平台一期', year: 2023, value: 680, status: '交付完成', role: '总包' },
    ],
    totalValue: 680, lastContact: '2026-03-18',
    renewal: { risk: 'low', riskName: '低风险', title: '二期AI大模型升级', value: 1500, date: '2026-Q3' },
    contacts: [{ name: '王建国', role: '采购处处长', relation: '良好', phone: '138****0001' }],
    suppliers: ['我司（主包）', '华为云（基础设施）', '中软国际（实施）'],
  },
  {
    id: 'CU002', name: '深圳市南山区政务服务数据管理局', abbr: '南山政数局',
    region: '广东省', city: '深圳市', type: '区级重点客户',
    projects: [
      { name: '南山区政务云平台建设', year: 2023, value: 950, status: '运维期', role: '总包' },
    ],
    totalValue: 950, lastContact: '2026-03-19',
    renewal: { risk: 'low', riskName: '低风险', title: '二期AI+数据要素升级', value: 1200, date: '2026-Q2' },
    contacts: [{ name: '陈志强', role: '副局长', relation: '深度合作', phone: '138****0002' }],
    suppliers: ['我司（主包）', '腾讯云（基础设施）'],
  },
  {
    id: 'CU003', name: '杭州市西湖区大数据局', abbr: '西湖区大数据局',
    region: '浙江省', city: '杭州市', type: '区级',
    projects: [
      { name: '西湖区政务数字底座建设', year: 2022, value: 420, status: '交付完成', role: '数据底座分包' },
    ],
    totalValue: 420, lastContact: '2025-12-15',
    renewal: { risk: 'medium', riskName: '中等', title: '关注：人事异动衍生拱墅区新建项目', value: null, date: null },
    contacts: [{ name: '刘勇', role: '原局长（已调任拱墅）', relation: '核心KP', phone: '138****0003' }],
    suppliers: ['我司（分包）', '海康威视（主包）'],
  },
  {
    id: 'CU004', name: '天津市滨海新区城市管理委员会', abbr: '滨海城管委',
    region: '天津市', city: '天津市', type: '区级',
    projects: [
      { name: '滨海新区数字城管平台一期', year: 2023, value: 380, status: '维保到期（2026-06）', role: '总包' },
    ],
    totalValue: 380, lastContact: '2026-03-19',
    renewal: { risk: 'medium', riskName: '中等', title: '二期智能化改造+维保续签', value: 650, date: '2026-Q2' },
    contacts: [{ name: '许明刚', role: '城管委主任', relation: '良好', phone: '138****0004' }],
    suppliers: ['我司（主包）', '科大讯飞（AI语音）'],
  },
]

export const events = [
  {
    id: 'E001', name: '2026中国数字政府大会', type: '高峰论坛',
    typeColor: 'red', location: '北京国家会议中心',
    startDate: '2026-03-25', endDate: '2026-03-26',
    organizer: '工业和信息化部', relevance: 'high', relevanceName: '高价值',
    description: '国内最高规格数字政府年度盛会，各省市大数据局长出席，是建立高层人脉的核心场景。',
    registered: true, expectedAttendees: '全国各省市大数据局长、信息化主管领导',
  },
  {
    id: 'E002', name: '2026粤港澳大湾区数字经济峰会', type: '区域峰会',
    typeColor: 'blue', location: '广州琶洲会展中心',
    startDate: '2026-04-10', endDate: '2026-04-11',
    organizer: '广东省政务服务数据管理局', relevance: 'high', relevanceName: '高价值',
    description: '聚焦大湾区数字政府建设与数据要素市场化，广东省及各市局长出席，是华南区重要客户关系维护场合。',
    registered: true, expectedAttendees: '广东省、深广佛等各市大数据局领导',
  },
  {
    id: 'E003', name: '2026智慧城市与大数据技术博览会（上海）', type: '展览博览',
    typeColor: 'green', location: '上海世博展览馆',
    startDate: '2026-04-20', endDate: '2026-04-22',
    organizer: '中国智慧城市产业联盟', relevance: 'medium', relevanceName: '中等价值',
    description: '以展览为主，可接触华东区潜在客户，适合展示新产品方案。',
    registered: false, expectedAttendees: '华东区政府采购负责人、集成商',
  },
  {
    id: 'E004', name: '全国大数据产业发展大会（贵阳数博会）', type: '高峰论坛',
    typeColor: 'purple', location: '贵阳国际会议中心',
    startDate: '2026-05-15', endDate: '2026-05-16',
    organizer: '国家数据局', relevance: 'medium', relevanceName: '中等价值',
    description: '国家数据局主办，重点展示数据要素市场化成果，可跟进多省市数据要素平台建设需求。',
    registered: false, expectedAttendees: '全国数据要素相关主管部门',
  },
  {
    id: 'E005', name: '2026中国政法智能化技术应用论坛', type: '行业论坛',
    typeColor: 'orange', location: '南京国际博览中心',
    startDate: '2026-06-05', endDate: '2026-06-06',
    organizer: '中国法学会', relevance: 'medium', relevanceName: '中等价值',
    description: '聚焦政法领域数字化，可拓展政法大数据新赛道客户资源。',
    registered: false, expectedAttendees: '各省市法院、检察院、公安等政法系统信息化负责人',
  },
]

const makeBriefing = (date, slice) => {
  const expanded = Array.from({ length: 20 }, (_, i) => slice[i % slice.length])

  return {
    id: `BR-${date.replace(/-/g, '')}`, date,
    title: `《智鹰ToG商机日报》· ${date}`,
    stats: {
      total: expanded.length,
      high: expanded.filter(l => l.score >= 80).length,
      medium: expanded.filter(l => l.score >= 60 && l.score < 80).length,
    },
    highlights: expanded.map((l, i) => ({ id: `${l.id}-${date}-${i + 1}`, title: l.title, score: l.score, type: l.typeName, nextAction: l.nextAction, region: l.region })),
    sentChannels: ['飞书', '企业微信'],
    conversionStats: {
      pushed: expanded.length,
      claimed: Math.ceil(expanded.length * 0.7),
      converted: Math.ceil(expanded.length * 0.3),
    },
  }
}

export const briefings = [
  ...Array.from({ length: 20 }, (_, i) => {
    const date = new Date('2026-03-21')
    date.setDate(date.getDate() - i)
    const dateStr = date.toISOString().split('T')[0]
    const start = (i * 2) % leads.length
    const size = 4 + (i % 3)
    const slice = Array.from({ length: size }, (_, k) => leads[(start + k) % leads.length])
    return makeBriefing(dateStr, slice)
  }),
]

export const dashboardStats = {
  totalLeads: leads.length,
  highPriority: leads.filter(l => l.score >= 80).length,
  contacting: leads.filter(l => l.status === 'contacting').length,
  filed: leads.filter(l => l.status === 'filed').length,
  todayLeads: leads.filter(l => l.createdAt === '2026-03-21').length,
  funnel: [
    { name: '线索池', value: leads.length, fill: '#1677ff' },
    { name: '接触中', value: leads.filter(l => l.status === 'contacting').length, fill: '#52c41a' },
    { name: '已立项', value: leads.filter(l => l.status === 'filed').length, fill: '#fa8c16' },
    { name: '招投标', value: bids.filter(b => b.statusKey === 'bidding').length, fill: '#f5222d' },
  ],
}

export const todos = [
  { id: 1, type: 'urgent', icon: '🔥', text: '广州市政务数据局采购意向公示，招标窗口期仅剩2周，请立即安排接触', leadId: 'L001', date: '今日' },
  { id: 2, type: 'reminder', icon: '📋', text: '南山区二期升级方案建议书需本周五前提交', leadId: 'L003', date: '03-22' },
  { id: 3, type: 'renewal', icon: '⏰', text: '天津滨海新区城管委维保合同6月到期，请加速推进续签谈判', leadId: 'L014', date: '03-25' },
  { id: 4, type: 'visit', icon: '🤝', text: '福建省大数据局技术交流会（下周三），需提前准备大模型Demo和部署方案', leadId: 'L009', date: '03-26' },
  { id: 5, type: 'event', icon: '🎯', text: '中国数字政府大会（3月25日）：重点拜访山东省大数据局孙副局长', leadId: 'L005', date: '03-25' },
]
